#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Context compilation tool for massive context window LLMs.

This script parses the sitemap file 'llms.txt' in the repository root,
extracts all referenced Markdown documentation files recursively, and
concatenates them into a single, unified 'llms-full.txt' file. This facilitates
one-shot, zero-turn context ingestion for massive-context models (e.g. Gemini Pro).
"""

# golden-path: ignore
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


def compile_llms_full(
    repo_root_str: str = ".", output_path_str: str | None = None
) -> bool:
    """Parses llms.txt and compiles all linked docs into llms-full.txt.

    Args:
        repo_root_str: The absolute or relative path to the repository root directory.
        output_path_str: Optional custom path to write the compiled sitemap.

    Returns:
        True if the compilation was successful, False otherwise.
    """
    repo_root = Path(repo_root_str).resolve()
    sitemap_path = repo_root / "llms.txt"
    output_path = (
        Path(output_path_str).resolve()
        if output_path_str
        else repo_root / "llms-full.txt"
    )

    if not sitemap_path.exists():
        print(f"[-] Sitemap not found: {sitemap_path}", file=sys.stderr)
        return False

    try:
        sitemap_content = sitemap_path.read_text(encoding="utf-8")
    except Exception as e:
        print(f"[-] Failed to read sitemap: {e}", file=sys.stderr)
        return False

    # Extract relative links to Markdown files (e.g. [AGENTS.md](AGENTS.md) or [docs/A.md](docs/A.md))
    link_pattern = re.compile(r"\[.*?\]\(([^)]+?\.md)\)")
    relative_paths = link_pattern.findall(sitemap_content)

    if not relative_paths:
        print("[-] No Markdown files found in sitemap.", file=sys.stderr)
        return False

    # Unique paths in order of appearance
    seen_paths = set()
    ordered_paths = []
    for rel_path_str in relative_paths:
        normalized_str = rel_path_str.strip()
        if normalized_str not in seen_paths:
            seen_paths.add(normalized_str)
            ordered_paths.append(normalized_str)

    compiled_blocks = []

    # Header block
    compiled_blocks.append(
        "# =========================================================================\n"
        "# SOVEREIGN FABRIC COMPLIED DOCUMENTATION INDEX\n"
        "# Generated automatically. DO NOT EDIT THIS FILE MANUALLY.\n"
        "# =========================================================================\n\n"
    )

    for rel_path_str in ordered_paths:
        file_path = repo_root / rel_path_str
        if not file_path.exists():
            print(f"[-] Reference document not found: {rel_path_str}", file=sys.stderr)
            continue

        try:
            file_content = file_path.read_text(encoding="utf-8")
        except Exception as e:
            print(
                f"[-] Failed to read reference document {rel_path_str}: {e}",
                file=sys.stderr,
            )
            continue

        # Append structured document block
        separator_start = (
            f"# =========================================================================\n"
            f"# START OF FILE: {rel_path_str}\n"
            f"# =========================================================================\n\n"
        )
        separator_end = (
            f"\n\n# =========================================================================\n"
            f"# END OF FILE: {rel_path_str}\n"
            f"# =========================================================================\n\n"
        )
        compiled_blocks.append(separator_start + file_content + separator_end)

    try:
        final_content = "".join(compiled_blocks).rstrip() + "\n"
        output_path.write_text(final_content, encoding="utf-8")
        print(
            f"[+] Successfully compiled {len(ordered_paths)} documents into: {output_path}"
        )
        return True
    except Exception as e:
        print(f"[-] Failed to write compiled output: {e}", file=sys.stderr)
        return False


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Compile unified massive context sitemap."
    )
    parser.add_argument("--repo-root", default=".", help="Path to repository root")
    args = parser.parse_args()

    success = compile_llms_full(args.repo_root)
    sys.exit(0 if success else 1)
