"""Provides the main entry point and core orchestration logic for executing the Assessment Engine's commercial pipeline."""

import sys

from assessment_engine.scripts.lib.pipeline_runtime import (
    build_runtime_env,
    resolve_python_bin,
    run_module_step,
)
from assessment_engine.scripts.lib.runtime_env import run_vertex_ai_preflight
from assessment_engine.scripts.lib.runtime_paths import (
    resolve_client_dir,
    resolve_commercial_report_payload_path,
    resolve_global_report_payload_path,
    resolve_global_report_template_path,
)


def main(argv: list[str] | None = None) -> None:
    """Orchestrates the end-to-end commercial assessment pipeline for a client.

    This function serves as the primary execution wrapper for generating a commercial
    "Account Action Plan". It sequentially performs the following operations:

    1.  Parses the client name from command-line arguments.
    2.  Resolves all required file paths for client-specific data payloads,
        report templates, and the final output document.
    3.  Builds a runtime environment from system variables.
    4.  Optionally runs a Vertex AI preflight check to validate cloud
        connectivity and model accessibility, unless explicitly skipped via the
        `ASSESSMENT_SKIP_VERTEX_PREFLIGHT` environment variable.
    5.  Executes a data refinement subprocess to ingest raw data and produce a
        structured, machine-readable data model.
    6.  Executes a report rendering subprocess to generate a final Microsoft
        Word document from the structured data model and a document template.

    Args:
        argv: A list of command-line arguments. If None, `sys.argv` is used.
            The second element (`argv[1]`) is expected to be the client name.

    Raises:
        SystemExit: If the `client_name` is not provided as a command-line
            argument.
        FileNotFoundError: If required input files or directories, such as
            client-specific payloads or the report template, do not exist.
        subprocess.CalledProcessError: If either the data refinement or the
            report rendering subprocess returns a non-zero exit code.
    """
    if len(argv if argv is not None else sys.argv) < 2:
        print("Uso: python -m scripts.run_commercial_pipeline <client_name>")
        sys.exit(1)

    client_name = (argv if argv is not None else sys.argv)[1]
    client_dir = resolve_client_dir(client_name)
    env = build_runtime_env()
    if env.get("ASSESSMENT_SKIP_VERTEX_PREFLIGHT", "").strip() != "1":
        preflight = run_vertex_ai_preflight(env=env)
        print(
            "✅ Vertex AI listo "
            f"(project={preflight['project']}, location={preflight['location']}, model={preflight['model']})"
        )

    global_payload_path = resolve_global_report_payload_path(client_name)
    commercial_payload_path = resolve_commercial_report_payload_path(client_name)
    template_path = resolve_global_report_template_path()
    output_path = client_dir / f"Account_Action_Plan_{client_name}.docx"

    python_bin = resolve_python_bin()

    # Initiates the multi-agent commercial refiner to ingest raw input data and produce a structured, machine-readable output.
    run_module_step(
        [
            python_bin,
            "-m",
            "assessment_engine.scripts.run_commercial_refiner",
            str(global_payload_path),
        ],
        "Multi-Agent Commercial Refinement",
        env,
    )

    # Renders the structured data model generated by the refiner into the final deliverable, a confidential Microsoft Word document compliant with the specified format.
    run_module_step(
        [
            python_bin,
            "-m",
            "assessment_engine.scripts.render_commercial_report",
            str(commercial_payload_path),
            str(template_path),
            str(output_path),
        ],
        "Render Account Action Plan",
        env,
    )

    print(
        f"\n¡Pipeline Comercial finalizado con éxito! Documento generado: {output_path}"
    )


if __name__ == "__main__":
    main()
