from pydantic import BaseModel, Field

from .common import VersionedPayload


class DealFlash(BaseModel):
    """{'docstring': 'Model the primary purchase driver and win theme for a deal flash.'}."""
    purchase_driver: str
    ntt_win_theme: str


class CommercialSummaryDraft(BaseModel):
    """Represents a draft of a commercial summary for a business deal.

    A data model capturing the key components for articulating the commercial
    viability and strategy of a business opportunity.

    Attributes:
        deal_flash: An object containing the core details of the deal.
        why_now_bullets: A sequence of strings articulating the timeliness and
            urgency of the deal.
        how_we_win_bullets: A sequence of strings outlining the strategy for success.
        estimated_tam: A string representation of the estimated Total Addressable
            Market (TAM).
    """
    deal_flash: DealFlash
    why_now_bullets: list[str]
    how_we_win_bullets: list[str]
    estimated_tam: str


class GtmStrategy(BaseModel):
    """Defines the Go-To-Market (GTM) strategy components."""
    trojan_horse: str
    self_funded_transformation: str
    lock_in: str


class StakeholderMatrixItem(BaseModel):
    """Model a stakeholder communication matrix entry, mapping a role to a focus and message."""
    role: str
    focus: str
    message: str


class AccountDirectorOutput(BaseModel):
    """A data model for the structured output from the Account Director persona.

    Attributes:
        commercial_summary: A data object containing the draft commercial summary.
        gtm_strategy: The proposed go-to-market (GTM) strategy.
        stakeholder_matrix: A list of objects identifying key stakeholders, their
            roles, and influence levels.
    """
    commercial_summary: CommercialSummaryDraft
    gtm_strategy: GtmStrategy
    stakeholder_matrix: list[StakeholderMatrixItem]


class OpportunityPipelineItem(BaseModel):
    """Represents a single item in a commercial opportunity pipeline.

    A data model for tracking and analyzing a potential sales or partnership
    opportunity.

    Attributes:
        initiative: Name or description of the commercial initiative.
        tower_origin: The originating business unit or team.
        vendor_cosell: Name of the vendor partner in a co-sell opportunity.
        revenue_type: The classification of expected revenue (e.g., 'Subscription').
        estimated_tcv: Estimated Total Contract Value (TCV), formatted as a string.
        cost_of_inaction: Estimated cost to the client for not pursuing the
            opportunity.
        client_objection: Primary objections raised by the potential client.
        objection_handling: The proposed strategy for addressing client objections.
    """
    initiative: str
    tower_origin: str
    vendor_cosell: str
    revenue_type: str
    estimated_tcv: str
    cost_of_inaction: str
    client_objection: str
    objection_handling: str


class PresalesArchitectOutput(BaseModel):
    """Model the structured output from a presales architect's analysis.

    Attributes:
        opportunities_pipeline: A list of identified sales opportunities and their
            associated pipeline stages.
    """
    opportunities_pipeline: list[OpportunityPipelineItem]


class ContextAndWhy(BaseModel):
    """Models the context and justification for a specific action or decision.

    Attributes:
        origin (str): The source, event, or rationale that necessitates an action.
        cost_of_inaction (str): A description of the anticipated negative
            consequences if the action is not taken.
    """
    origin: str
    cost_of_inaction: str


class SolutionAndWhat(BaseModel):
    """Define the target state and north-star metric for a strategic solution."""
    target_state: str
    north_star_metric: str


class EngagementManagerOutput(BaseModel):
    """Represents a structured proposal generated by an Engagement Manager persona.

    This data model serves as a container for the two primary components of a
    client proposal: an analysis of the customer's current situation and a
    detailed outline of the proposed solution.

    Attributes:
        context_and_why (ContextAndWhy): An object detailing the customer's
            context and the underlying rationale for the proposed engagement.
        solution_and_what (SolutionAndWhat): An object detailing the specific
            solution being proposed and its constituent parts.
    """
    context_and_why: ContextAndWhy
    solution_and_what: SolutionAndWhat


class ScopeAndHow(BaseModel):
    """Defines project phases, deliverables, and out-of-scope items."""
    phases: list[str]
    deliverables: list[str]
    out_of_scope: list[str]


class DeliveryTeam(BaseModel):
    """Represent a delivery team defined by a list of member roles."""
    team_roles: list[str]


class LeadSolutionsArchitectOutput(BaseModel):
    """Defines the structured data model for the output of a Lead Solutions Architect analysis.

    This data model encapsulates the primary components of a technical solution
    proposal, including the project scope, the required delivery team, and the
    overarching strategy for AI transformation.

    Attributes:
        scope_and_how: A detailed project scope definition and the corresponding
            execution methodology.
        delivery_team: The composition of the proposed delivery team, including roles
            and responsibilities.
        ai_transformation_strategy: A high-level narrative outlining the strategic
            approach to AI transformation.
    """
    scope_and_how: ScopeAndHow
    delivery_team: DeliveryTeam
    ai_transformation_strategy: str


class GovernanceAndAssumptions(BaseModel):
    """Represent governance and assumption details."""
    governance_model: str
    assumptions: list[str]


class RiskManagementItem(BaseModel):
    """{'docstring': 'Represent a single risk and its corresponding mitigation strategy.'}."""
    risk: str
    mitigation: str


class DeliveryAndRiskDirectorOutput(BaseModel):
    """Models the consolidated output for project delivery and risk management.

    This data model encapsulates the key components of a project's delivery
    strategy, including its governance framework, risk mitigation plan, and
    deployment sequence.

    Attributes:
        governance_and_assumptions: The governance framework and underlying
            assumptions for the project delivery.
        risk_management: A sequence of identified risks and their corresponding
            mitigation strategies.
        activation_plan: An ordered sequence of steps or milestones for project
            deployment.
    """
    governance_and_assumptions: GovernanceAndAssumptions
    risk_management: list[RiskManagementItem]
    activation_plan: list[str]


class WhyNttData(BaseModel):
    """Model the data for the 'Why NTT DATA' section."""
    accelerators: list[str]
    partnerships: str


class InvestmentAndTimeline(BaseModel):
    """Represent the estimated investment and timeline for a project or engagement."""
    estimated_duration: str
    tcv_range: str


class SalesPartnerOutput(BaseModel):
    """Represents the structured data model for a sales partner proposal.

    This model encapsulates the primary components of a formal sales proposal,
    including the value proposition, financial investment, project timeline, and
    a concise executive summary.

    Attributes:
        why_ntt_data: The value proposition and key differentiators for the
            engagement.
        investment_and_timeline: The financial investment requirements and
            projected project timeline.
        executive_synthesis: A concise summary of the proposal intended for
            executive review.
    """
    why_ntt_data: WhyNttData
    investment_and_timeline: InvestmentAndTimeline
    executive_synthesis: str


class ProposalDraft(BaseModel):
    """Represents the structured data for a commercial proposal draft.

    This Pydantic model aggregates the distinct sections required to construct a
    comprehensive and standardized commercial proposal document.

    Attributes:
        initiative_name (str): The name of the proposed project or initiative.
        context_and_why (ContextAndWhy): The business context and rationale for the
            initiative.
        solution_and_what (SolutionAndWhat): A detailed description of the proposed
            solution and its components.
        scope_and_how (ScopeAndHow): The defined scope of work and the methodology
            for its delivery.
        delivery_team (DeliveryTeam): Details of the team responsible for project
            execution.
        ai_transformation_strategy (str): The high-level strategy for AI
            transformation associated with the proposal.
        governance_and_assumptions (GovernanceAndAssumptions): The project
            governance model and key underlying assumptions.
        risk_management (list[RiskManagementItem]): A list of identified risks
            and their corresponding mitigation strategies.
        activation_plan (list[str]): A sequence of steps outlining the project
            activation plan.
        why_ntt_data (WhyNttData): The value proposition for selecting NTT DATA for
            this engagement.
        investment_and_timeline (InvestmentAndTimeline): Details of the required
            financial investment and the project timeline.
        executive_synthesis (str): A concise summary of the proposal for
            executive review.
    """
    initiative_name: str
    context_and_why: ContextAndWhy
    solution_and_what: SolutionAndWhat
    scope_and_how: ScopeAndHow
    delivery_team: DeliveryTeam
    ai_transformation_strategy: str
    governance_and_assumptions: GovernanceAndAssumptions
    risk_management: list[RiskManagementItem]
    activation_plan: list[str]
    why_ntt_data: WhyNttData
    investment_and_timeline: InvestmentAndTimeline
    executive_synthesis: str


class CommercialDocumentMeta(BaseModel):
    """Represent metadata for a commercial document."""
    client: str
    date: str
    version: str


class CommercialPayload(VersionedPayload):
    """Represents the structured data payload for a commercial strategy document.

    This class encapsulates all components required for generating, managing, and
    versioning a commercial document. It inherits versioning information from
    the `VersionedPayload` base class.

    Attributes:
        meta: An instance of `CommercialDocumentMeta` containing metadata.
        commercial_summary: A `CommercialSummaryDraft` object detailing the summary.
        gtm_strategy: A `GtmStrategy` object outlining the go-to-market plan.
        stakeholder_matrix: A list of `StakeholderMatrixItem` objects,
            defaulting to an empty list.
        opportunities_pipeline: A list of `OpportunityPipelineItem` objects.
        proactive_proposals: A list of `ProposalDraft` objects.
        intelligence_dossier: A dictionary for market and competitive
            intelligence data, defaulting to an empty dictionary.
    """
    meta: CommercialDocumentMeta
    commercial_summary: CommercialSummaryDraft
    gtm_strategy: GtmStrategy
    stakeholder_matrix: list[StakeholderMatrixItem] = Field(default_factory=list)
    opportunities_pipeline: list[OpportunityPipelineItem]
    proactive_proposals: list[ProposalDraft]
    intelligence_dossier: dict = Field(default_factory=dict)
