/**
 * Sovereign Strategic Terminal V11 - State Engine (Boardroom Integrity Fix)
 * Corrects the mapping to the 'strategy' and 'roadmap' objects generated by Python.
 */

window.TerminalState = (function() {
    let _raw = {}; // This will hold the nexus-data
    let _dto = {}; // This will hold the topology

    function init() {
        try {
            const nexusEl = document.getElementById('nexus-data');
            const dtoEl = document.getElementById('dto-state');

            if (nexusEl) _raw = JSON.parse(nexusEl.textContent);
            if (dtoEl) _dto = JSON.parse(dtoEl.textContent);

            console.log("🛠️ Terminal V11.1 Hydrated", {
                strategy: !!_raw.strategy,
                roadmap: !!_raw.roadmap,
                nodes: _dto.topology?.nodes?.length
            });

            window.dispatchEvent(new CustomEvent('terminal-ready'));
        } catch (e) {
            console.error("❌ Critical Hydration Error", e);
        }
    }

    return {
        init,
        get raw() { return _raw; },
        get apex() {
            // Mapping to the 'strategy' object from Python
            const s = _raw.strategy || {};
            return {
                maturity: s.global_score || "3.0",
                risks: s.burning_platform?.length || 0,
                headline: s.headline || "Strategic Assessment Report",
                narrative: s.narrative || "Analysis in progress."
            };
        },
        get topology() {
            return _dto.topology || { nodes: [], edges: [] };
        },
        get heatmap() {
            return _raw.heatmap || [];
        },
        get roadmap() {
            // Mapping to horizons inside roadmap
            return _raw.roadmap?.horizons || {};
        },
        get burningPlatform() {
            return _raw.strategy?.burning_platform || [];
        },
        get businessImpacts() {
            return _raw.strategy?.business_impacts || [];
        },
        getWaveZero() {
            const horizons = _raw.roadmap?.horizons || {};
            return (horizons.quick_wins_0_3_months || []).slice(0, 5);
        }
    };
})();
